environment:
  secure_file_version: 1.0.1
  my_secret:
    secure: XwupaTEU6vRyeuB7ZOOniA==
  my_salt:
    secure: Zxm5GDkhuz8HYLnA0G4RV1eaBxptWCbGUFLIEGytdPF9ryvuM4w=
  my_gcp_secret:
    secure: zkVb0HH9YV7arn4DrfEoiYSywjIyzpjT0n7OJaN/n5Y=
  my_gcp_salt:
    secure: STXopp4a0aI3JjAyA4S1V7Z1UDkfnXk2hZkqADE2CDbPvo2YvTtF/Jjjqzd7GQN9s72TvfG6d8Fdc78GdLldsQ==
  WHITESOURCE_API_KEY:
    secure: DO9//hUqoDrq1k/+HIdZbekwNKsQXJoB/xT5A5okWYTa4Xoe51grKd81nS3ysR8pouujgWd2n8YAJoRHXCjYTajeyv+UgUy9wUQ51hOhhsM=

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

skip_tags: true

init:
- set appveyor_full_version=%secure_file_version%.%appveyor_build_number%
- appveyor UpdateBuild -Version %appveyor_full_version%

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
- build.cmd
- 7z a secure-file.zip %APPVEYOR_BUILD_FOLDER%\build\*
- appveyor PushArtifact secure-file.zip

test: off

deploy:
- provider: GitHub
  tag: $(secure_file_version)
  release: Secure File $(secure_file_version)
  auth_token:
    secure: avf7rJ4eX9x4b5bE/CX/nL6rQgUnNhSGTxxqMt+KyPU3yeOhHIE8q8NtmO10YOae
  force_update: true